### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by MagdalenaDeschner** [claymation/python-builtwith#9]
Hello,

I'm loving your product and would like to use it. However using the following Python and builtwith version:
# Name                    Version                   Build  
builtwith                 1.3.3                    pypi_0    
python                    3.7.3                h8c8aaf0_0

However, trying to import the BuiltWith class fails with the following error:
ImportError: cannot import name 'BuiltWith' from 'builtwith'

Do you have an idea whats wrong?

**Comment by claymation** [comment]
Sorry about that. It probably doesn't work with Python 3. I haven't used this in quite a while.

**Comment by richstokes** [comment]
Similar issue here when following the README;

```ImportError: cannot import name 'BuiltWith' from partially initialized module 'builtwith' (most likely due to a circular import) (builtwith.py)
```

Also on python3. Python 2 is end of life so not sure why you wouldn't use 3?

**Comment by claymation** [comment]
```
> ImportError: cannot import name 'BuiltWith' from partially initialized module 'builtwith' (most likely due to a circular import) (builtwith.py)
> ```

Works for me:

```
% python3 -m virtualenv venv
% source venv/bin/activate  
(venv) % pip install python-builtwith
(venv) % python
Python 3.7.3 (default, Mar  6 2020, 22:34:30) 
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from builtwith import BuiltWith
>>> bw = BuiltWith(key='example')
>>> bw.lookup('example.com')
...
```

> Also on python3. Python 2 is end of life so not sure why you wouldn't use 3?

Because I wrote it seven years ago.
